
default:
	# Set default make action here
	# xcodebuild -target Tests -configuration MyMainTarget -sdk macosx build	

clean:
	-rm -rf build/*

test:
	GHUNIT_AUTORUN=1 GHUNIT_AUTOEXIT=1 xcodebuild -target Tests -configuration Debug -sdk macosx build
