// This file auto-generated by ghunit gem
#import <UIKit/UIKit.h>

int main(int argc, char *argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil, @"GHUnitIOSAppDelegate");
  }
}
